defmodule Gumroad.Sale do
  @moduledoc """
  A Gumroad sale.

  See the [Gumroad docs](https://app.gumroad.com/api#sales) for more info.
  """

  @type affiliate :: %{
          email: String.t(),
          amount: String.t()
        }

  @type t :: %__MODULE__{
          id: String.t(),
          email: String.t(),
          seller_id: String.t(),
          timestamp: String.t(),
          daystamp: String.t(),
          created_at: String.t(),
          product_name: String.t(),
          product_has_variants: boolean(),
          price: number(),
          gumroad_fee: number(),
          subscription_duration: String.t(),
          formatted_display_price: String.t(),
          formatted_total_price: String.t(),
          currency_symbol: String.t(),
          amount_refundable_in_currency: number(),
          product_id: String.t(),
          product_permalink: String.t(),
          partially_refunded: boolean(),
          chargedback: boolean(),
          purchase_email: String.t(),
          zip_code: number(),
          paid: boolean(),
          has_variants: boolean(),
          variants: map() | nil,
          variants_and_quantity: String.t(),
          has_custom_fields: boolean(),
          custom_fields: map(),
          order_id: number(),
          is_product_physical: boolean(),
          purchaser_id: String.t(),
          is_recurring_billing: boolean(),
          can_contact: boolean(),
          is_following: boolean(),
          disputed: boolean(),
          dispute_won: boolean(),
          is_additional_contribution: boolean(),
          discover_fee_charged: boolean(),
          is_gift_sender_purchase: boolean(),
          is_gift_receiver_purchase: boolean(),
          referrer: String.t(),
          card: map(),
          product_rating: nil,
          reviews_count: number(),
          average_rating: number(),
          subscription_id: String.t(),
          cancelled: boolean(),
          ended: boolean(),
          recurring_charge: boolean(),
          license_key: String.t(),
          license_id: String.t(),
          license_disabled: boolean(),
          affiliate: affiliate() | nil,
          quantity: 1
        }

  defstruct [
    :id,
    :email,
    :seller_id,
    :timestamp,
    :daystamp,
    :created_at,
    :product_name,
    :product_has_variants,
    :price,
    :gumroad_fee,
    :subscription_duration,
    :formatted_display_price,
    :formatted_total_price,
    :currency_symbol,
    :amount_refundable_in_currency,
    :product_id,
    :product_permalink,
    :partially_refunded,
    :chargedback,
    :purchase_email,
    :zip_code,
    :paid,
    :has_variants,
    :variants,
    :variants_and_quantity,
    :has_custom_fields,
    :custom_fields,
    :order_id,
    :is_product_physical,
    :purchaser_id,
    :is_recurring_billing,
    :can_contact,
    :is_following,
    :disputed,
    :dispute_won,
    :is_additional_contribution,
    :discover_fee_charged,
    :is_gift_sender_purchase,
    :is_gift_receiver_purchase,
    :referrer,
    :card,
    :product_rating,
    :reviews_count,
    :average_rating,
    :subscription_id,
    :cancelled,
    :ended,
    :recurring_charge,
    :license_key,
    :license_id,
    :license_disabled,
    :affiliate,
    :quantity
  ]

  def new(body) do
    %__MODULE__{
      id: Map.fetch!(body, "id"),
      email: Map.get(body, "email"),
      seller_id: Map.get(body, "seller_id"),
      timestamp: Map.get(body, "timestamp"),
      daystamp: Map.get(body, "daystamp"),
      created_at: Map.get(body, "created_at"),
      product_name: Map.get(body, "product_name"),
      product_has_variants: Map.get(body, "product_has_variants"),
      price: Map.get(body, "price"),
      gumroad_fee: Map.get(body, "gumroad_fee"),
      subscription_duration: Map.get(body, "subscription_duration"),
      formatted_display_price: Map.get(body, "formatted_display_price"),
      formatted_total_price: Map.get(body, "formatted_total_price"),
      currency_symbol: Map.get(body, "currency_symbol"),
      amount_refundable_in_currency: Map.get(body, "amount_refundable_in_currency"),
      product_id: Map.get(body, "product_id"),
      product_permalink: Map.get(body, "product_permalink"),
      partially_refunded: Map.get(body, "partially_refunded"),
      chargedback: Map.get(body, "chargedback"),
      purchase_email: Map.get(body, "purchase_email"),
      zip_code: Map.get(body, "zip_code"),
      paid: Map.get(body, "paid"),
      has_variants: Map.get(body, "has_variants"),
      variants: Map.get(body, "variants"),
      variants_and_quantity: Map.get(body, "variants_and_quantity"),
      has_custom_fields: Map.get(body, "has_custom_fields"),
      custom_fields: Map.get(body, "custom_fields"),
      order_id: Map.get(body, "order_id"),
      is_product_physical: Map.get(body, "is_product_physical"),
      purchaser_id: Map.get(body, "purchaser_id"),
      is_recurring_billing: Map.get(body, "is_recurring_billing"),
      can_contact: Map.get(body, "can_contact"),
      is_following: Map.get(body, "is_following"),
      disputed: Map.get(body, "disputed"),
      dispute_won: Map.get(body, "dispute_won"),
      is_additional_contribution: Map.get(body, "is_additional_contribution"),
      discover_fee_charged: Map.get(body, "discover_fee_charged"),
      is_gift_sender_purchase: Map.get(body, "is_gift_sender_purchase"),
      is_gift_receiver_purchase: Map.get(body, "is_gift_receiver_purchase"),
      referrer: Map.get(body, "referrer"),
      card: Map.get(body, "card"),
      product_rating: Map.get(body, "product_rating"),
      reviews_count: Map.get(body, "reviews_count"),
      average_rating: Map.get(body, "average_rating"),
      subscription_id: Map.get(body, "subscription_id"),
      cancelled: Map.get(body, "cancelled"),
      ended: Map.get(body, "ended"),
      recurring_charge: Map.get(body, "recurring_charge"),
      license_key: Map.get(body, "license_key"),
      license_id: Map.get(body, "license_id"),
      license_disabled: Map.get(body, "license_disabled"),
      affiliate:
        Map.get(body, "affiliate")
        |> case do
          nil ->
            nil

          affiliate ->
            %{
              email: Map.get(affiliate, "email"),
              amount: Map.get(affiliate, "amount")
            }
        end,
      quantity: Map.get(body, "quantity")
    }
  end
end
