name: CI
on:
  push:
    branches: ["master"]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "24"
          elixir-version: "1.13.4"
      - uses: actions/cache@v2
        id: mix-cache
        with:
          path: |
            deps
            _build
          key: mix-cache-v2-${{ hashFiles('mix.lock') }}
      - run: mix deps.get && mix deps.compile
      - run: mix format --check-formatted
      - run: mix credo
      - name: Test
        env:
          GUMROAD_TEST_ACCESS_TOKEN: ${{ secrets.GUMROAD_TEST_ACCESS_TOKEN }}
        run: mix test --trace --include live
